import {account,admin,identity,ApiError,apiFailure,json,one,now,settings,transaction,checkRequest,limit,expireDrafts,db} from '@/lib/server';
import {textValue as txt,moneyCents,validateIban,normalizePhone,safeUrl,videoIdentity,fee} from '@/lib/validation';
const stmt=(sql:string,...args:any[])=>({sql,args});
const need=(ok:unknown,message:string)=>{if(!ok)throw new ApiError(message,400)};
export async function POST(req:Request){try{await checkRequest(req);const raw=await req.text();need(raw.length<40000,'İstek çok büyük.');const b=JSON.parse(raw),a=txt(b.action),rid=txt(b.requestId,16,80),id=await identity();await limit(id.userId,60);const prior=await one('SELECT actor,action FROM operations WHERE id=?',rid);if(prior){if(prior.actor!==id.userId||prior.action!==a)throw new ApiError('İşlem kimliği kullanılmış.',409);return json({ok:true,replayed:true});}const time=now();
if(a==='onboard'){need(b.communityVisibility===undefined||['public','hidden'].includes(b.communityVisibility),'Topluluk görünürlüğünü seç.');need(['creator','clipper'].includes(b.role),'Bir hesap türü seç.');need(b.accepted===true,'18 yaş ve üzeri olduğunu ve koşulları kabul ettiğini onayla.');need(!await one('SELECT id FROM users WHERE id=?',id.userId),'Profilin zaten oluşturulmuş.');await transaction(id.userId,a,rid,id.userId,[stmt('INSERT INTO users(id,email,name,role,created_at,social_url,phone,community_visible) VALUES(?,?,?,?,?,?,?,?)',id.userId,id.email,txt(b.name,2,100),b.role,time,b.socialUrl?safeUrl(b.socialUrl):'',normalizePhone(b.phone),b.communityVisibility==='hidden'?0:1)]);return json({ok:true});}
if(a==='setup'){await limit('setup:'+id.userId,5,3600);need(!await one('SELECT 1 FROM admin_owner WHERE slot=1'),'Yönetici kurulumu daha önce tamamlandı.');const secret=process.env.KLIPFON_SETUP_SECRET;need(secret&&secret.length>=32,'Yönetici kurulum anahtarı henüz tanımlanmamış.');const digest=async(s:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).join(',');need(await digest(String(b.secret||''))===await digest(secret!),'Kurulum kodu geçersiz.');await transaction(id.userId,a,rid,id.userId,[stmt("INSERT INTO users(id,email,name,role,created_at) VALUES(?,?,?,'admin',?) ON CONFLICT(id) DO UPDATE SET role='admin',status='active'",id.userId,id.email,id.fullName||id.email,time),stmt('INSERT INTO admin_owner(slot,user_id,created_at) VALUES(1,?,?)',id.userId,time)]);return json({ok:true});}
const u=await account();const s=await settings();if(s.maintenance&&u.role!=='admin'&&!['ticket','profile'].includes(a))throw new ApiError('Yeni işlemler kısa süreliğine durduruldu. Mevcut kayıtların korunuyor.',503);
let statements:{sql:string,args:any[]}[]=[],target=String(b.id||rid),details='';
const creator=()=>need(u.role==='creator','Bu işlem yayıncı hesapları içindir.');const clipper=()=>need(u.role==='clipper','Bu işlem klipper hesapları içindir.');
switch(a){
case 'profile':{need(b.communityVisibility===undefined||['public','hidden'].includes(b.communityVisibility),'Topluluk görünürlüğünü seç.');const visible=b.communityVisibility===undefined?u.community_visible:b.communityVisibility==='public'?1:0;const iban=String(b.iban||'').replace(/\s/g,'').toUpperCase();need(!iban||validateIban(iban),'Geçerli bir Türkiye IBAN’ı gir.');const social=b.socialUrl?safeUrl(b.socialUrl):'';statements=[stmt('UPDATE users SET name=?,bio=?,phone=?,iban=?,account_name=?,verified=CASE WHEN social_url=? THEN verified ELSE 0 END,social_url=?,community_visible=? WHERE id=?',txt(b.name,2,100),b.bio===undefined?u.bio:txt(b.bio,0,300),normalizePhone(b.phone),iban,iban?txt(b.accountName,3,150):'',social,social,visible,u.id)];target=u.id;break;}
case 'deposit':{creator();need(s.depositsEnabled&&s.iban&&s.beneficiary,'Banka bilgileri ve ödeme kabulü henüz açılmadı.');const amount=moneyCents(b.amount,100,100000000);if(b.proofId)need(await one('SELECT id FROM uploads WHERE id=? AND user_id=?',b.proofId,u.id),'Dekont bulunamadı.');const reference='KPF-'+rid.replace(/-/g,'').slice(0,12).toUpperCase();statements=[stmt('INSERT INTO deposits(id,user_id,amount,sender,transfer_date,reference,bank_snapshot,proof_id,created_at) VALUES(?,?,?,?,?,?,?,?,?)',rid,u.id,amount,txt(b.sender,3,150),txt(b.transferDate,10,30),reference,JSON.stringify({iban:s.iban,beneficiary:s.beneficiary,bank:s.bank}),b.proofId||null,time)];break;}
case 'campaign_create':{creator();need(b.rights===true,'Kaynak içerik için kullanım yetkini onayla.');const budget=moneyCents(b.budget,10000),cap=moneyCents(b.cap,100),rate=moneyCents(b.rate,1,100000);need(cap<=budget,'Klip limiti toplam havuzdan büyük olamaz.');need(['YouTube','Instagram','TikTok'].includes(b.platform),'Platform seç.');statements=[stmt('INSERT INTO campaigns(id,owner_id,title,description,rules,source_url,platform,category,budget,cap,rate,fee_bps,created_at,deadline) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',rid,u.id,txt(b.title,5,100),txt(b.description,30,3000),txt(b.rules,20,5000),safeUrl(b.sourceUrl),b.platform,txt(b.category,2,50),budget,cap,rate,s.feeBps,time,time+864000)];break;}
case 'campaign_status':{const c=await one('SELECT * FROM campaigns WHERE id=?',b.id);need(c,'Kampanya bulunamadı.');need(c!.owner_id===u.id||u.role==='admin','Bu kampanyayı yönetemezsin.');need(['paused','active','closed'].includes(b.status),'Geçersiz kampanya durumu.');if(c!.status==='pending')await admin();await expireDrafts();statements=[stmt('UPDATE campaigns SET status=? WHERE id=?',b.status,b.id)];break;}
case 'join':{clipper();need(u.social_url,'Kampanyaya katılmadan önce profilinden paylaşım yapacağın sosyal hesap bağlantısını ekle.');need(b.accepted===true,'Kampanya şartlarını kabul et.');await expireDrafts();const c=await one('SELECT * FROM campaigns WHERE id=?',b.id);need(c&&c.status==='active','Kampanya katılıma açık değil.');statements=[stmt('INSERT INTO clips(id,campaign_id,user_id,cap,created_at,expires_at) VALUES(?,?,?,?,?,?)',rid,b.id,u.id,c!.cap,time,time+172800)];break;}
case 'clip_draft':{clipper();const c=await one('SELECT * FROM clips WHERE id=? AND user_id=?',b.id,u.id);need(c&&c.status==='draft'&&c.expires_at>=time,'Taslak gönderim süresi veya durumu uygun değil.');statements=[stmt("UPDATE clips SET draft_url=?,status='submitted',note='' WHERE id=?",safeUrl(b.url),b.id)];break;}
case 'clip_publish':{clipper();const c=await one('SELECT k.*,c.platform FROM clips k JOIN campaigns c ON c.id=k.campaign_id WHERE k.id=? AND k.user_id=?',b.id,u.id);need(c&&c.status==='ready'&&c.expires_at>=time,'Bu klip için yayın onayı veya süresi uygun değil.');const pub=Math.floor(new Date(b.publishedAt).getTime()/1000);need(Number.isFinite(pub)&&pub<=time+60&&pub>=time-172800&&pub>=c!.created_at,'Yayın tarihini doğru gir; bağlantıyı 48 saat içinde göndermelisin.');const url=safeUrl(b.url),key=videoIdentity(url,c!.platform);statements=[stmt("UPDATE clips SET status='published',video_url=?,video_key=?,published_at=?,measurement_ends=?,review_ends=? WHERE id=?",url,key,pub,pub+1209600,pub+1814400,b.id)];break;}
case 'clip_cancel':{clipper();need(await one("SELECT 1 FROM clips WHERE id=? AND user_id=? AND status IN ('draft','ready')",b.id,u.id),'Bu klip iptal edilemez.');statements=[stmt("UPDATE clips SET status='cancelled' WHERE id=?",b.id)];break;}
case 'withdraw':{need(u.role!=='admin','Yönetici hesabından çekim talep edilemez.');need(validateIban(u.iban)&&u.account_name,'Önce profilinden kendi IBAN ve alıcı bilgilerini kaydet.');statements=[stmt('INSERT INTO withdrawals(id,user_id,amount,iban,account_name,created_at) VALUES(?,?,?,?,?,?)',rid,u.id,moneyCents(b.amount,1),u.iban,u.account_name,time)];break;}
case 'ticket':{statements=[stmt('INSERT INTO tickets(id,user_id,subject,message,reference,created_at,updated_at) VALUES(?,?,?,?,?,?,?)',rid,u.id,txt(b.subject,3,150),txt(b.message,10,5000),String(b.reference||'').slice(0,100),time,time)];break;}
case 'draft_review':{const c=await one('SELECT k.*,c.owner_id FROM clips k JOIN campaigns c ON c.id=k.campaign_id WHERE k.id=?',b.id);need(c&&c.status==='submitted','Klip taslak incelemesinde değil.');need(c!.owner_id===u.id||u.role==='admin','Bu klibi inceleyemezsin.');need(['ready','rejected'].includes(b.status),'Geçersiz karar.');const note=b.status==='rejected'?txt(b.note,5,1000):String(b.note||'').slice(0,1000);statements=[stmt('UPDATE clips SET status=?,expires_at=?,note=? WHERE id=?',b.status,time+172800,note,b.id)];details=note;break;}
default:{await admin();
 switch(a){
 case 'settings':{const iban=String(b.iban||'').replace(/\s/g,'').toUpperCase();need(!iban||validateIban(iban),'Geçerli bir Türkiye IBAN’ı gir.');const feeBps=Number(b.feeBps);need(Number.isInteger(feeBps)&&feeBps>=0&&feeBps<=10000,'Komisyon oranı 0–100 arasında olmalı.');const next={...s,iban,beneficiary:String(b.beneficiary||'').trim().slice(0,150),bank:String(b.bank||'').trim().slice(0,100),contactEmail:String(b.contactEmail||'').trim().slice(0,150),companyName:String(b.companyName||'').trim().slice(0,200),companyAddress:String(b.companyAddress||'').trim().slice(0,1000),taxInfo:String(b.taxInfo||'').trim().slice(0,200),feeBps,depositsEnabled:b.depositsEnabled===true,maintenance:b.maintenance===true,termsText:String(b.termsText||'').slice(0,12000),privacyText:String(b.privacyText||'').slice(0,12000)};if(next.contactEmail)need(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(next.contactEmail),'İletişim e-postası geçersiz.');if(next.depositsEnabled)need(iban&&next.beneficiary&&next.companyName&&next.companyAddress&&next.taxInfo&&next.contactEmail&&next.termsText.length>=100&&next.privacyText.length>=100,'Ödeme kabulünü açmadan önce banka, işletme ve onaylı sözleşme/aydınlatma metinlerini tamamla.');statements=[stmt("INSERT INTO settings(key,value) VALUES('main',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value",JSON.stringify(next))];details='Banka, işletme ve işlem ayarları güncellendi.';break;}
 case 'deposit_review':{need(['approved','rejected'].includes(b.status),'Geçersiz karar.');const d=await one('SELECT * FROM deposits WHERE id=?',b.id);need(d&&d.status==='pending','Bildirim artık beklemede değil.');const note=b.status==='rejected'?txt(b.note,5,1000):String(b.note||'').slice(0,1000);const ref=b.status==='approved'?txt(b.bankRef,5,150):null;need(b.status!=='approved'||b.confirmed===true,'Banka hesabında tahsilatı doğruladığını onayla.');statements=[stmt('UPDATE deposits SET status=?,note=?,bank_ref=?,reviewed_at=?,reviewed_by=? WHERE id=?',b.status,note,ref,time,u.id,b.id)];details=note;break;}
 case 'campaign_review':{need(['active','rejected'].includes(b.status),'Geçersiz karar.');need(await one("SELECT 1 FROM campaigns WHERE id=? AND status='pending'",b.id),'Kampanya artık onay beklemiyor.');const note=b.status==='rejected'?txt(b.note,5,1000):String(b.note||'').slice(0,1000);statements=[stmt('UPDATE campaigns SET status=?,note=?,deadline=? WHERE id=?',b.status,note,time+864000,b.id)];details=note;break;}
 case 'user_review':{need(b.id!==u.id,'Kendi yönetici hesabını değiştiremezsin.');const user=await one('SELECT * FROM users WHERE id=?',b.id);need(user&&user.role!=='admin','Kullanıcı bulunamadı.');need(['active','suspended'].includes(b.status),'Geçersiz durum.');if(b.verified)need(user!.social_url,'Kullanıcı önce sosyal hesap bağlantısını eklemeli.');statements=[stmt('UPDATE users SET status=?,verified=? WHERE id=?',b.status,b.verified?1:0,b.id)];details=txt(b.note,5,1000);break;}
 case 'measure':{const clip=await one('SELECT * FROM clips WHERE id=?',b.id);need(clip&&clip.status==='published','Klip ölçüm aşamasında değil.');const total=Number(b.totalViews),eligible=Number(b.eligibleViews);need(Number.isSafeInteger(total)&&Number.isSafeInteger(eligible)&&total>=eligible&&eligible>=0&&total<=1000000000,'Görüntülenme sayılarını kontrol et.');const observed=Math.floor(new Date(b.observedAt).getTime()/1000);need(Number.isFinite(observed)&&observed<=time+60&&observed>=clip!.published_at&&observed<=clip!.measurement_ends,'Gözlem tarihi 14 günlük ölçüm aralığında olmalı.');statements=[stmt('INSERT INTO measurements(id,clip_id,total_views,eligible_views,source,note,observed_at,created_at,actor) VALUES(?,?,?,?,?,?,?,?,?)',rid,b.id,total,eligible,txt(b.source,5,500),txt(b.note,10,2000),observed,time,u.id)];details='Manuel ölçüm kaydı eklendi.';break;}
 case 'settle':{const clip=await one('SELECT k.*,c.rate FROM clips k JOIN campaigns c ON c.id=k.campaign_id WHERE k.id=?',b.id);need(clip&&clip.status==='published','Klip kesinleştirilebilir durumda değil.');need(b.confirmed===true,'Hakediş incelemesini tamamladığını onayla.');const amount=Math.min(clip!.cap,Math.floor(clip!.eligible_views*clip!.rate/1000));statements=[stmt("UPDATE clips SET status='settled',earned=?,settled_at=?,note=? WHERE id=?",amount,time,txt(b.note,10,2000),b.id)];details='Hakediş kesinleştirildi.';break;}
 case 'clip_reject':{need(await one("SELECT 1 FROM clips WHERE id=? AND status='published'",b.id),'Klip ölçümde değil.');const note=txt(b.note,10,2000);statements=[stmt("UPDATE clips SET status='rejected',note=? WHERE id=?",note,b.id)];details=note;break;}
 case 'withdrawal_review':{need(['processing','paid','rejected'].includes(b.status),'Geçersiz durum.');const note=b.status==='rejected'?txt(b.note,5,1000):String(b.note||'').slice(0,1000);if(b.status==='paid')need(b.confirmed===true,'Banka transferinin tamamlandığını onayla.');statements=[stmt('UPDATE withdrawals SET status=?,bank_ref=?,note=?,reviewed_at=?,reviewed_by=? WHERE id=?',b.status,b.status==='paid'?txt(b.bankRef,5,150):null,note,time,u.id,b.id)];details=note;break;}
 case 'ticket_reply':{statements=[stmt("UPDATE tickets SET response=?,status='answered',updated_at=? WHERE id=?",txt(b.response,5,5000),time,b.id)];break;}
 default:throw new ApiError('İşlem bulunamadı.',404);
 }}
}
await transaction(u.id,a,rid,target,statements,details);return json({ok:true,id:target});
}catch(e){return apiFailure(e)}}
