import {database,allowedOrigin} from '@/lib/runtime';
import {getCurrentUser} from '@/lib/auth';
export type Row=Record<string,any>;
export function db(){return database;}
export const now=()=>Math.floor(Date.now()/1000);
export async function one(sql:string,...args:any[]):Promise<Row|null>{return db().prepare(sql).bind(...args).first();}
export async function rows(sql:string,...args:any[]):Promise<Row[]>{return (await db().prepare(sql).bind(...args).all()).results as Row[];}
export class ApiError extends Error{status:number;constructor(message:string,status=400){super(message);this.status=status;}}
export async function identity(){const u=await getCurrentUser();if(!u)throw new ApiError('Devam etmek için giriş yap.',401);return u;}
export async function account(){const identityUser=await identity();const u=await one('SELECT * FROM users WHERE id=?',identityUser.userId);if(!u)throw new ApiError('Önce profilini tamamla.',428);if(u.status==='suspended')throw new ApiError('Hesabın askıya alındı. Destek ekibiyle görüş.',403);return u;}
export async function admin(){const u=await account();if(u.role!=='admin'||!await one('SELECT 1 FROM admin_owner WHERE user_id=?',u.id))throw new ApiError('Bu alan yalnızca yöneticilere açık.',403);return u;}
export const defaults={iban:'',beneficiary:'',bank:'',contactEmail:'',companyName:'',companyAddress:'',taxInfo:'',feeBps:2000,depositsEnabled:false,maintenance:false,termsText:'',privacyText:''};
export async function settings(){const s=await one("SELECT value FROM settings WHERE key='main'");return {...defaults,...(s?JSON.parse(s.value):{})};}
export async function balance(id:string){return Number((await one('SELECT COALESCE(SUM(amount),0) AS balance FROM ledger WHERE user_id=?',id))?.balance||0);}
export const campaignSelect=`SELECT c.*,u.name AS owner_name,COALESCE((SELECT SUM(CASE WHEN k.status='settled' THEN k.earned WHEN k.status IN ('draft','submitted','ready','published') THEN k.cap ELSE 0 END) FROM clips k WHERE k.campaign_id=c.id),0) AS used,(SELECT COUNT(*) FROM clips k WHERE k.campaign_id=c.id) AS clip_count FROM campaigns c JOIN users u ON u.id=c.owner_id`;
export async function expireDrafts(){await db().prepare("UPDATE clips SET status='expired',note='48 saat içinde taslak gönderilmedi.' WHERE status='draft' AND expires_at<?").bind(now()).run();await db().prepare("UPDATE clips SET status='expired',note='Yayın onayından sonra 48 saat içinde bağlantı gönderilmedi.' WHERE status='ready' AND expires_at<?").bind(now()).run();}
export function json(data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});}
export function apiFailure(e:unknown){const msg=e instanceof Error?e.message:'İşlem tamamlanamadı.';if(e instanceof ApiError)return json({error:msg},e.status);const known=['CHAT_UNAVAILABLE','MESSAGES_IMMUTABLE','BALANCE_LOW','CAPACITY_FULL','INVALID_TRANSITION','CAMPAIGN_HAS_ACTIVE_CLIPS','IMMUTABLE_LEDGER','NOT_VERIFIED','MEASUREMENT_PENDING','ALREADY_CLOSED'];const tr:Record<string,string>={CHAT_UNAVAILABLE:'Mesaj gönderilemiyor. İstek onayı, mesaj tercihi veya engelleme durumunu kontrol et.',MESSAGES_IMMUTABLE:'Mesajlar silinemez veya değiştirilemez.',BALANCE_LOW:'Kullanılabilir bakiye yetersiz.',CAPACITY_FULL:'Bu kampanyada ayrılabilir bütçe kalmadı.',INVALID_TRANSITION:'Bu işlem kayıt durumuyla uyuşmuyor. Sayfayı yenile.',CAMPAIGN_HAS_ACTIVE_CLIPS:'Devam eden klipler sonuçlanmadan kampanya kapatılamaz.',IMMUTABLE_LEDGER:'Muhasebe kayıtları değiştirilemez.',NOT_VERIFIED:'Önce sosyal medya hesabının doğrulanması gerekiyor.',MEASUREMENT_PENDING:'Ölçüm ve inceleme süresi henüz tamamlanmadı.',ALREADY_CLOSED:'Bu kayıt zaten kapatılmış.'};for(const k of known)if(msg.includes(k))return json({error:tr[k]},409);if(msg.includes('UNIQUE constraint'))return json({error:'Bu kayıt veya banka işlem referansı daha önce kullanıldı.'},409);if(msg.includes('D1_')||msg.includes('SQLITE')||msg.includes('binding')){console.error('Klipfon operation failed',msg.slice(0,200));return json({error:'İşlem şu anda tamamlanamadı. Bilgilerinizi koruyup tekrar deneyin.'},503);}return json({error:msg},400);}
export async function checkRequest(req:Request){const origin=req.headers.get('origin');if(!origin||!allowedOrigin(req))throw new ApiError('İstek kaynağı doğrulanamadı.',403);if(!req.headers.get('content-type')?.includes('application/json'))throw new ApiError('Geçersiz istek biçimi.',415);if(Number(req.headers.get('content-length')||0)>40000)throw new ApiError('İstek çok büyük.',413);}
export async function limit(key:string,max=50,seconds=60){const t=now(),k=key+':'+Math.floor(t/seconds);const r=await db().prepare('INSERT INTO rate_limits(key,count,expires) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count').bind(k,t+seconds).first<Row>();if(Number(r?.count)>max)throw new ApiError('Çok sık işlem yapılıyor. Bir dakika sonra tekrar dene.',429);await db().prepare('DELETE FROM rate_limits WHERE expires<?').bind(t-3600).run();}
export async function transaction(actor:string,action:string,requestId:string,target:string,statements:{sql:string,args:any[]}[],details=''){if(!/^[a-zA-Z0-9-]{16,80}$/.test(requestId))throw Error('İşlem kimliği geçersiz. Sayfayı yenile.');const prior=await one('SELECT * FROM operations WHERE id=?',requestId);if(prior){if(prior.actor!==actor||prior.action!==action)throw new ApiError('İşlem kimliği kullanılmış.',409);return;}const time=now();await db().batch([db().prepare('INSERT INTO operations(id,actor,action,created_at) VALUES(?,?,?,?)').bind(requestId,actor,action,time),...statements.map(s=>db().prepare(s.sql).bind(...s.args)),db().prepare('INSERT INTO audit(id,actor,action,target,details,created_at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),actor,action,target,details,time)]);}
