'use client';
import {useState,useEffect,useCallback} from 'react';
import {money,date} from './shared';
export function NotificationCenter(){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[page,setPage]=useState(1);
 const load=useCallback(async()=>{try{const r=await fetch('/api/notifications?page='+page),d=await r.json();if(!r.ok)throw Error(d.error);setData(d)}catch(e){setError(e instanceof Error?e.message:'Bildirimler yüklenemedi.')}},[page]);
 useEffect(()=>{void load();const t=setInterval(()=>{if(!document.hidden)void load()},15000);return()=>clearInterval(t)},[load]);
 async function read(id?:string){await fetch('/api/notifications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(id?{id}:{all:true})});await load();}
 return <div className="stack"><div className="row"><p>{data?.unread||0} okunmamış bildirim</p><button className="btn btn-small btn-secondary" onClick={()=>read()}>Tümünü okundu işaretle</button></div>{error&&<p className="error">{error}</p>}{data?.items.map((n:any)=><article key={n.id} className={'panel '+(!n.read_at?'notification-new':'')}><div className="row"><strong>{n.title}</strong><span className="hint">{date(n.created_at)}</span></div>{n.body&&<p className="whitespace-pre-wrap">{n.body}</p>}<a className="muted-link" href={n.href} onClick={()=>void read(n.id)}>İlgili kaydı aç →</a>{!n.read_at&&<button className="muted-link ml-5" onClick={()=>read(n.id)}>Okundu</button>}</article>)}{data&&!data.items.length&&<p>Henüz bildirim yok. Klip onayı, teslim süresi, ödeme ve mesaj gelişmeleri burada görünür.</p>}<div className="action-row"><button className="btn btn-small" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Önceki</button><span>{page}/{data?.pages||1}</span><button className="btn btn-small" disabled={page>=(data?.pages||1)} onClick={()=>setPage(p=>p+1)}>Sonraki</button></div></div>;
}
export function NotificationBadge(){
 const [count,setCount]=useState(0);
 useEffect(()=>{const load=()=>fetch('/api/notifications').then(r=>r.ok?r.json():null).then(d=>{if(d)setCount(d.unread)}).catch(()=>{});void load();const t=setInterval(()=>{if(!document.hidden)void load()},30000);return()=>clearInterval(t)},[]);
 return <a className="community-entry-link" href="/panel?bolum=notifications">Bildirimler {count>0&&<span className="pill">{count>99?'99+':count}</span>}</a>;
}
export function EarningsCalendar(){
 const [data,setData]=useState<any>(null),[error,setError]=useState('');
 const load=useCallback(async()=>{try{const r=await fetch('/api/earnings'),d=await r.json();if(!r.ok)throw Error(d.error);setData(d)}catch(e){setError(e instanceof Error?e.message:'Yüklenemedi.')}},[]);
 useEffect(()=>{void load()},[load]);const sum=(phase:string)=>data?.items.filter((c:any)=>c.phase===phase).reduce((a:number,c:any)=>a+c.estimate,0)||0;
 return <div className="stack"><div className="row"><p>Kazancının hangi aşamada olduğunu ve sıradaki tarihi takip et.</p><button className="btn btn-small btn-secondary" onClick={load}>Yenile</button></div>{error&&<p className="error">{error}</p>}<div className="stats-grid"><div className="stat-card"><small>Ölçümde · tahmini</small><strong>{money(sum('measuring'))}</strong></div><div className="stat-card"><small>İncelemede · tahmini</small><strong>{money(sum('review'))}</strong></div><div className="stat-card purple"><small>Çekilebilir bakiye</small><strong>{money(data?.available||0)}</strong></div></div><div className="notice">14 günlük ölçümün ardından 7 günlük inceleme yapılır. Tarihin dolması otomatik ödeme anlamına gelmez; yönetici hakedişi kesinleştirir. Tahmini tutarlar son uygun görüntülenme ölçümüne dayanır ve değişebilir.</div>{!!data?.pendingWithdrawals.length&&<div className="panel"><h3>Çekim için ayrılan tutar</h3><p>{money(data.pendingWithdrawals.reduce((a:number,w:any)=>a+w.amount,0))} · Çekilebilir bakiyeden ayrıdır.</p></div>}{data?.items.map((c:any)=><article className="panel" key={c.id}><div className="row"><a className="muted-link" href={'/kampanya/'+c.campaign_id}>{c.title}</a><span className="pill">{c.phase==='settled'?'Kesinleşti':c.phase==='measuring'?'Ölçümde':c.awaitingAdmin?'Yönetici kararı bekliyor':'İncelemede'}</span></div><h3 className="mt-4">{money(c.phase==='settled'?c.earned:c.estimate)} {c.phase!=='settled'&&<small>tahmini</small>}</h3><p>Ölçüm bitişi: {date(c.measurement_ends)}<br/>İnceleme bitişi: {date(c.review_ends)}{c.settled_at&&<><br/>Kesinleşme: {date(c.settled_at)}</>}</p><p className="hint">Son ölçüm: {date(c.last_measured_at)} · {c.phase==='settled'?'Bu kayıt geçmiş kazancındır; mevcut çekilebilir bakiyen yukarıdadır.':'Henüz çekilebilir bakiyeye eklenmedi.'}</p></article>)}{data&&!data.items.length&&<p>Yayınladığın kliplerin kazanç takvimi burada görünecek.</p>}</div>;
}
