'use client';
import {useState} from 'react';
import {Field,Pick,CheckField} from './forms';
export function AuthForm({mode,role='clipper',returnTo='/panel'}:{mode:'login'|'register'|'recover',role?:string,returnTo?:string}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[code,setCode]=useState(''),[copied,setCopied]=useState(false);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError('');const f=new FormData(e.currentTarget);try{const r=await fetch('/api/auth/'+mode,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...Object.fromEntries(f.entries()),accepted:f.get('accepted')==='on'})});const data=await r.json();if(!r.ok)throw Error(data.error||'İşlem tamamlanamadı.');if(data.recoveryCode)setCode(data.recoveryCode);else window.location.assign(returnTo);}catch(err){setError(err instanceof Error?err.message:'Bağlantı kurulamadı.');}finally{setBusy(false)}}
 if(code)return <div className="stack"><h3>Kurtarma kodunu güvenli bir yere kaydet.</h3><p>Şifreni unutursan bu kodla yenileyebilirsin. Kod yalnızca burada gösterilir; hesabına erişim sağlar. Kimseyle paylaşma.</p><div className="notice code break-all">{code}</div><button className="btn btn-secondary" onClick={async()=>{try{await navigator.clipboard.writeText(code);setCopied(true)}catch{setError('Kodu seçip elle kopyalayabilirsin.')}}}>{copied?'Kopyalandı':'Kodu kopyala'}</button>{error&&<p role="alert">{error}</p>}<a className="btn" href={mode==='recover'?'/giris':returnTo}>{mode==='recover'?'Giriş yap':'Kodumu kaydettim, devam et'}</a></div>;
 return <form onSubmit={submit} className="space-y-5">{mode==='register'&&<Field label="Adın / yayıncı adın"><input name="name" minLength={2} maxLength={100} required autoComplete="name"/></Field>}<Field label="E-posta adresin"><input name="email" type="email" required maxLength={254} autoComplete="username"/></Field>{mode==='register'&&<><Field label="Telefon numaran (zorunlu)" hint="Türkiye: 05xx xxx xx xx. Diğer ülkeler: +ülke kodu. Numaran yalnızca sen ve yetkili yönetim tarafından görülür."><input name="phone" type="tel" inputMode="tel" required maxLength={40} autoComplete="tel" placeholder="05xx xxx xx xx"/></Field><Field label="Klipfon’u nasıl kullanacaksın?"><Pick name="role" defaultValue={role==='creator'?'creator':'clipper'} options={[["clipper","Klipper — Klip üretip kazanmak"],["creator","Yayıncı — Kampanya açmak"]]}/></Field></>}{mode==='recover'&&<Field label="Kurtarma kodun"><input name="recoveryCode" type="password" required maxLength={100} autoComplete="off"/></Field>}<Field label={mode==='recover'?'Yeni şifren':'Şifren'} hint={mode==='login'?undefined:'En az 12 karakter kullan.'}><input name="password" type="password" required minLength={12} maxLength={128} autoComplete={mode==='login'?'current-password':'new-password'}/></Field>{mode==='register'&&<CheckField name="accepted">18 yaş ve üzerindeyim. <a className="muted-link" href="/kosullar" target="_blank">Kullanım koşullarını</a> kabul ediyorum ve <a className="muted-link" href="/gizlilik" target="_blank">gizlilik açıklamasını</a> okudum.</CheckField>}{error&&<div className="error" role="alert">{error}</div>}<button type="submit" className="btn w-full" disabled={busy}>{busy?'İşlem yapılıyor…':mode==='register'?'Hesabımı oluştur':mode==='recover'?'Şifremi yenile':'Giriş yap'}</button>{mode==='login'&&<div className="row"><a className="muted-link" href={'/kayit?return_to='+encodeURIComponent(returnTo)+'&rol='+role}>Hesap oluştur</a><a className="muted-link" href="/kurtarma">Şifremi unuttum</a></div>}{mode!=='login'&&<a className="muted-link block" href="/giris">Giriş ekranına dön</a>}</form>
}
