'use client';
import {useState,useEffect} from 'react';
import {date} from './shared';
export function BackupPanel(){
 const [data,setData]=useState<any>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const load=async()=>{const r=await fetch('/api/admin/backups'),d=await r.json();if(!r.ok)throw Error(d.error);setData(d)};
 useEffect(()=>{load().catch(e=>setMessage(e.message))},[]);
 async function act(name?:string){setBusy(true);setMessage('');try{const r=await fetch('/api/admin/backups',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(name?{action:'verify',name}:{action:'create'})}),d=await r.json();if(!r.ok)throw Error(d.error);setMessage('Geri yükleme kontrolü başarılı: arşiv ayrı bir alana açıldı; veritabanı, mesajlar ve dosyalar doğrulandı.');await load();}catch(e){setMessage(e instanceof Error?e.message:'İşlem tamamlanamadı.')}finally{setBusy(false)}}
 return <div className="stack"><div className="notice">Sunucu çalışırken her gün otomatik yedek alınır; son 7 arşiv tutulur. Arşivler hesapları, para hareketlerini, mesajları ve yüklenen dosyaları içerir. Her yedek ayrı bir alana açılarak doğrulanır. Sunucu diski kaybına karşı arşivi indirip ayrı ve güvenli bir yerde sakla.</div><button className="btn" disabled={busy} onClick={()=>act()}>{busy?'İşlem sürüyor…':'Şimdi yedek al ve doğrula'}</button>{message&&<p role="status" className="notice">{message}</p>}{data?.items.map((b:any)=><article className="panel" key={b.name}><strong>{date(b.createdAt)}</strong><p>{(b.size/1024/1024).toFixed(2)} MB · {b.verified?'Geri yükleme doğrulandı':'Kontrol bekliyor'}</p><p className="hint">{b.counts.users||0} kullanıcı · {b.counts.messages||0} mesaj · {b.counts.ledger||0} muhasebe kaydı</p><div className="action-row"><a className="btn btn-small btn-secondary" href={'/api/admin/backups?download='+encodeURIComponent(b.name)}>Arşivi indir</a><button className="btn btn-small btn-secondary" disabled={busy} onClick={()=>act(b.name)}>Geri yüklemeyi tekrar kontrol et</button></div></article>)}{data&&!data.items.length&&<p>Henüz yedek yok.</p>}<div className="panel"><h3>Gerçek geri yükleme</h3><p>Bu panel canlı veritabanını üzerine yazmaz. Kurtarmada uygulama durdurulur, mevcut veri dizini korunur, doğrulanmış arşiv boş veri dizinine açılır ve uygulama aynı sürümle başlatılır. Kullanıcı, mesaj ve muhasebe sayıları karşılaştırılmadan trafik yeniden açılmaz.</p></div></div>;
}
