'use client';
import {useState,useEffect} from 'react';
import {money} from './shared';
const templates=[{title:'Yayının öne çıkan anları',category:'Oyun',description:'İzinli yayın kaydından eğlenceli, anlaşılır ve bağlamı koruyan kısa videolar üret.',rules:'15–60 saniye; okunabilir Türkçe altyazı; konuşmanın bağlamını koru. İzinsiz müzik kullanma. Paylaşım açıklamasında ücretli iş birliğini belirt.'},{title:'Podcastten kısa hikâyeler',category:'Podcast',description:'İzinli podcast bölümündeki dikkat çekici fikirleri kısa ve anlaşılır kliplere dönüştür.',rules:'20–60 saniye; konuşmacıyı doğru belirt; cümleleri anlamını değiştirecek şekilde kesme. Müzik ve konuk izinleri kapsamındaki bölümleri kullan. Ücretli iş birliğini açıkla.'},{title:'Bir dakikada faydalı bilgi',category:'Eğitim',description:'İzinli eğitim içeriğinden tek bir konuyu net biçimde anlatan kısa videolar hazırla.',rules:'20–60 saniye; altyazı ve kaynak adı ekle. İddiaları abartma; içeriğin bağlamını koru. Ücretli iş birliğini belirt.'}];
export function CampaignPlanner({onUse}:{onUse:(data:any)=>void}){
 const [drafts,setDrafts]=useState<any[]>([]),[error,setError]=useState('');
 useEffect(()=>{fetch('/api/campaign-drafts').then(r=>r.json()).then(d=>setDrafts(d.items||[])).catch(()=>setError('Taslaklar yüklenemedi.'))},[]);
 return <section className="panel mb-6"><h3>İlk kampanyanı hazırla</h3><p>Bir başlangıç metni seç; kendi kaynak içeriğini, bütçeni ve kurallarını ekle. Taslak kaydetmek bütçe ayırmaz ve kampanyayı yayınlamaz.</p>{error&&<p className="error">{error}</p>}<div className="action-row">{templates.map(t=><button className="btn btn-small btn-secondary" key={t.title} onClick={()=>onUse({...t,platform:'YouTube'})}>{t.title}</button>)}</div>{!!drafts.length&&<div className="stack mt-5"><strong>Kaydedilmiş taslakların</strong>{drafts.map(d=><button className="btn btn-secondary" key={d.id} onClick={()=>onUse({...JSON.parse(d.payload),draftId:d.id})}>{JSON.parse(d.payload).title||'Adsız taslak'} · düzenle</button>)}</div>}</section>;
}
export function SaveCampaignDraft({draftId}:{draftId?:string}){
 const [status,setStatus]=useState(''),[busy,setBusy]=useState(false);
 async function save(e:React.MouseEvent<HTMLButtonElement>){const form=e.currentTarget.form;if(!form)return;setBusy(true);try{const payload=Object.fromEntries(new FormData(form)),r=await fetch('/api/campaign-drafts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:draftId,payload,requestId:crypto.randomUUID()})}),d=await r.json();if(!r.ok)throw Error(d.error);setStatus('Taslak kaydedildi. Bütçe ayrılmadı; kampanya yayınlanmadı.');}catch(e){setStatus(e instanceof Error?e.message:'Kaydedilemedi.')}finally{setBusy(false)}}
 return <div className="stack"><button type="button" className="btn btn-secondary" disabled={busy} onClick={save}>Taslak olarak kaydet</button>{status&&<p role="status" className="hint">{status}</p>}</div>;
}
export function LaunchChecklist(){
 const [data,setData]=useState<any>(null);useEffect(()=>{fetch('/api/admin/launch').then(r=>r.json()).then(setData)},[]);
 if(!data)return <p>Açılış kontrolü yükleniyor…</p>;
 return <div className="stack"><div className="notice">Gerçek kampanya için aktif yayıncı hesabı, izinli kaynak içerik, yayıncının belirlediği ücret/limit ve yeterli yatırılmış bakiye gerekir. Kampanyalar yayıncı panelinden incelemeye gönderilir; yönetici onayıyla açılır.</div><div className="stats-grid"><div className="stat-card"><small>Yayıncı hesabı</small><strong>{data.creators?.length||0}</strong></div><div className="stat-card"><small>Hazırlanan taslak</small><strong>{data.drafts?.length||0}</strong></div><div className="stat-card"><small>Aktif kampanya</small><strong>{data.campaigns?.filter((c:any)=>c.status==='active').length||0}</strong></div></div>{!data.paymentsReady&&<div className="notice">Havale kabulü kapalı. Gerçek kampanya bütçesi yüklenmeden önce banka ve işletme ayarları tamamlanmalı.</div>}{data.creators?.map((u:any)=><div className="panel" key={u.id}><strong>{u.name}</strong><p>Kullanılabilir bakiye: {money(u.balance)} · {u.status==='active'?'Aktif':'Askıda'}</p></div>)}{data.drafts?.map((d:any)=><div className="panel" key={d.id}><h3>{JSON.parse(d.payload).title||'Adsız taslak'}</h3><p>{d.name} · Henüz bütçe ayrılmadı</p><p className="whitespace-pre-wrap">{JSON.parse(d.payload).description}</p><p>{JSON.parse(d.payload).sourceUrl?'Kaynak bağlantısı girilmiş':'Kaynak içerik eksik'} · {JSON.parse(d.payload).budget?'Bütçe taslağı girilmiş':'Bütçe eksik'}</p></div>)}</div>;
}
