'use client';
import {useRef,useState} from 'react';
import {toast} from 'sonner';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {LoaderCircle} from 'lucide-react';
export function Field({label,hint,children,full=false}:{label:string,hint?:string,children:React.ReactNode,full?:boolean}){return <label className={'form-field '+(full?'full':'')}><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
export function Pick({name,label,options,defaultValue,onChange}:{name:string,label?:string,options:string[][],defaultValue?:string,onChange?:(v:string)=>void}){return <Select name={name} defaultValue={defaultValue} onValueChange={onChange}><SelectTrigger className="w-full min-h-[46px] bg-[#0f1015] text-sm" aria-label={label||name}><SelectValue placeholder="Seç"/></SelectTrigger><SelectContent>{options.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select>}
export function CheckField({name,children,defaultChecked=false}:{name:string,children:React.ReactNode,defaultChecked?:boolean}){return <label className="flex items-start gap-3 text-sm leading-6 cursor-pointer"><Checkbox name={name} className="mt-1 shrink-0" defaultChecked={defaultChecked}/><span>{children}</span></label>}
export function ActionForm({action,id,children,onDone,label='Kaydet',extra={},danger=false}:{action:string,id?:string,children?:React.ReactNode,onDone?:()=>void,label?:string,extra?:Record<string,unknown>,danger?:boolean}){const [busy,setBusy]=useState(false),[error,setError]=useState('');const rid=useRef('');async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError('');const f=new FormData(e.currentTarget);const data:Record<string,any>=Object.fromEntries(f.entries());for(const key of ['accepted','rights','confirmed','verified','depositsEnabled','maintenance'])data[key]=f.get(key)==='on';if(data.feePercent!==undefined)data.feeBps=Math.round(Number(data.feePercent)*100);rid.current||=crypto.randomUUID();try{const r=await fetch('/api/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,...extra,action,id,requestId:rid.current})});const d:any=await r.json();if(!r.ok)throw Error(d.error||'İşlem tamamlanamadı.');rid.current='';toast.success('İşlem kaydedildi.');onDone?.();}catch(e){setError(e instanceof Error?e.message:'Bağlantı kurulamadı. Tekrar deneyebilirsin.')}finally{setBusy(false)}}return <form onSubmit={submit} className="space-y-5">{children}{error&&<div className="error" role="alert">{error}</div>}<div className="form-actions"><button disabled={busy} className={'btn '+(danger?'btn-danger':'')} type="submit">{busy&&<LoaderCircle size={16} className="animate-spin"/>}{busy?'Kaydediliyor…':label}</button></div></form>}
export function Modal({title,description,open,onClose,children}:{title:string,description:string,open:boolean,onClose:()=>void,children:React.ReactNode}){return <Dialog open={open} onOpenChange={v=>{if(!v)onClose()}}><DialogContent className="sm:max-w-xl max-h-[90vh] overflow-y-auto rounded-2xl p-6"><DialogHeader><DialogTitle className="text-xl">{title}</DialogTitle><DialogDescription className="text-sm leading-6">{description}</DialogDescription></DialogHeader>{children}</DialogContent></Dialog>}
export function ReceiptUpload({onChange}:{onChange:(id:string)=>void}){const [status,setStatus]=useState('');const [busy,setBusy]=useState(false);return <Field label="Dekont (isteğe bağlı)" hint="PDF, JPG veya PNG · en fazla 5 MB. Yalnızca sen ve yönetici görebilir."><input aria-label="Dekont yükle" type="file" accept=".pdf,.png,.jpg,.jpeg" disabled={busy} onChange={async e=>{const f=e.target.files?.[0];if(!f)return;setBusy(true);setStatus('Yükleniyor…');const data=new FormData();data.set('file',f);try{const r=await fetch('/api/upload',{method:'POST',body:data});const d:any=await r.json();if(!r.ok)throw Error(d.error);onChange(d.id);setStatus('Dekont yüklendi.')}catch(err){setStatus(err instanceof Error?err.message:'Yüklenemedi.');onChange('')}finally{setBusy(false)}}}/><small role="status">{status}</small></Field>}
