'use client';
import {useState,useEffect} from 'react';
import {date} from './shared';
const statuses:any={open:'Açık',reviewing:'İnceleniyor',resolved:'Sonuçlandı',dismissed:'İşlem gerektirmiyor'};
export function ReportButton({targetType,targetId}:{targetType:string;targetId:string}){
 const [open,setOpen]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function send(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{const r=await fetch('/api/reports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({targetType,targetId,category:f.get('category'),reason:f.get('reason'),requestId:crypto.randomUUID()})}),d=await r.json();if(!r.ok)throw Error(d.error);setMessage('Şikâyetin kaydedildi. Panelindeki Şikâyetlerim bölümünden takip edebilirsin.');setOpen(false);}catch(e){setMessage(e instanceof Error?e.message:'Şikâyet kaydedilemedi.')}finally{setBusy(false)}}
 return <div className="mt-3"><button className="muted-link text-xs" type="button" onClick={()=>setOpen(!open)}>Şikâyet et</button>{message&&<p role="status" className="hint">{message}</p>}{open&&<form className="stack mt-3" onSubmit={send}><select name="category" className="field-input" aria-label="Şikâyet türü"><option value="spam">Spam / rahatsız etme</option><option value="impersonation">Taklit hesap</option><option value="photo">Uygunsuz profil fotoğrafı</option><option value="copyright">İzinsiz / kopya içerik</option><option value="illegal">Yasa dışı faaliyet şüphesi</option><option value="other">Diğer</option></select><textarea name="reason" aria-label="Şikâyet açıklaması" required minLength={10} maxLength={2000} placeholder="Ne olduğunu ve ilgili ayrıntıları yaz…"/><button className="btn btn-small btn-secondary" disabled={busy}>Şikâyeti gönder</button></form>}</div>;
}
export function Reports({admin=false}:{admin?:boolean}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[page,setPage]=useState(1),[filter,setFilter]=useState('all');
 const load=async()=>{try{const r=await fetch((admin?'/api/admin/reports':'/api/reports')+'?page='+page+'&status='+filter),d=await r.json();if(!r.ok)throw Error(d.error);setData(d);}catch(e){setError(e instanceof Error?e.message:'Yüklenemedi.')}};
 useEffect(()=>{void load()},[admin,page,filter]);
 async function review(e:React.FormEvent<HTMLFormElement>,id:string){e.preventDefault();const f=new FormData(e.currentTarget);try{const r=await fetch('/api/admin/reports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status:f.get('status'),note:f.get('note'),requestId:crypto.randomUUID()})}),d=await r.json();if(!r.ok)throw Error(d.error);await load();}catch(e){setError(e instanceof Error?e.message:'Kaydedilemedi.')}}
 return <div className="stack">{admin&&<select className="field-input" aria-label="Şikâyet durumu" value={filter} onChange={e=>{setFilter(e.target.value);setPage(1)}}><option value="all">Tüm şikâyetler</option>{Object.entries(statuses).map(([v,l])=><option key={v} value={v}>{String(l)}</option>)}</select>}<button className="btn btn-small btn-secondary" onClick={load}>Yenile</button>{error&&<p className="error">{error}</p>}{data?.items.map((r:any)=><article className="panel" key={r.id}><div className="row"><h3>{r.target_type==='profile'?'Profil':r.target_type==='clip'?'Klip':'Mesaj'} şikâyeti</h3><span className="pill">{statuses[r.status]}</span></div><p className="hint">{date(r.created_at)} {admin?' · '+r.reporter_name:''}</p><p className="whitespace-pre-wrap">{r.reason}</p>{r.admin_note&&<div className="notice">Yönetim: {r.admin_note}</div>}{admin&&<><details className="my-4"><summary>İlgili kayıt / kanıt</summary><pre className="report-evidence">{JSON.stringify(JSON.parse(r.evidence),null,2)}</pre>{r.target_type==='profile'&&<a className="muted-link" href={'/topluluk/'+r.target_id}>Profili aç</a>}{r.target_type==='message'&&<a className="muted-link" href={'/admin?bolum=chat&chat='+JSON.parse(r.evidence).conversation_id}>Konuşmayı aç</a>}<a className="muted-link block" href="/admin?bolum=users">Kullanıcı yönetimi / askıya alma</a></details><form onSubmit={e=>review(e,r.id)} className="stack"><select name="status" className="field-input" aria-label="Şikâyet kararı" defaultValue="reviewing"><option value="reviewing">İncelemeye al</option><option value="resolved">Sonuçlandı</option><option value="dismissed">İşlem gerektirmiyor</option></select><textarea name="note" required minLength={5} maxLength={2000} placeholder="Şikâyet eden üyeye gösterilecek karar ve gerekçe"/><button className="btn btn-small">Kararı kaydet</button></form></>}</article>)}{data&&!data.items.length&&<p>Henüz şikâyet kaydı yok.</p>}{admin&&data&&<div className="action-row"><button className="btn btn-small" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Önceki</button><span>{page}/{data.pages}</span><button className="btn btn-small" disabled={page>=data.pages} onClick={()=>setPage(p=>p+1)}>Sonraki</button></div>}</div>;
}
