'use client';
import {ArrowUpRight,Inbox,Check,Copy} from 'lucide-react';
import {useState} from 'react';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {Progress} from '@/components/ui/progress';
export const money=(c:number=0)=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:2}).format(c/100);
export const date=(v:number|string)=>v?new Date(typeof v==='number'?v*1000:v).toLocaleString('tr-TR',{dateStyle:'medium',timeStyle:'short'}):'—';
export const labels:Record<string,string>={pending:'İncelemede',active:'Katılıma açık',paused:'Katılım durduruldu',closed:'Tamamlandı',rejected:'Reddedildi',approved:'Onaylandı',draft:'Taslak bekleniyor',submitted:'Taslak incelemede',ready:'Yayın onayı verildi',published:'Ölçümde',settled:'Kesinleşti',expired:'Süre doldu',cancelled:'İptal edildi',paid:'Ödendi',processing:'Transfer hazırlanıyor',open:'Yanıt bekleniyor',answered:'Yanıtlandı',creator:'Yayıncı',clipper:'Klipper',admin:'Yönetici',suspended:'Askıya alındı'};
export function Status({value}:{value:string}){return <span className={'pill '+(['active','approved','paid','settled','answered'].includes(value)?'pill-green':['rejected','suspended','cancelled'].includes(value)?'pill-red':['pending','submitted','processing'].includes(value)?'pill-amber':'')}>{labels[value]||value}</span>}
export function Brand(){return <a href="/" className="brand" aria-label="Klipfon ana sayfa"><img src="/brand/klipfon-wordmark-dark.png" alt="Klipfon" width={172} height={57} style={{width:172,height:57,objectFit:'contain'}}/></a>}
export function Header(){return <header className="wrap topbar"><Brand/><nav className="navlinks"><a className="desktop-link" href="/#kampanyalar">Kampanyalar</a><a className="desktop-link" href="/#nasil-calisir">Nasıl çalışır?</a><a className="desktop-link" href="/yardim">Yardım</a><a href="/giris" className="btn btn-secondary">Giriş yap <ArrowUpRight size={16}/></a></nav></header>}
export function Footer(){return <footer className="wrap site-footer"><Brand/><div className="footer-links"><a href="/yardim">Yardım</a><a href="/kosullar">Kullanım koşulları</a><a href="/gizlilik">Gizlilik</a><a href="/admin">Yönetim</a></div><span>© {new Date().getFullYear()} Klipfon</span></footer>}
export function InfoEmpty({title,description,children}:{title:string,description:string,children?:React.ReactNode}){return <Empty className="border border-dashed border-border rounded-2xl p-8"><EmptyHeader><Inbox size={26} className="text-primary mx-auto mb-3"/><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{description}</EmptyDescription></EmptyHeader>{children}</Empty>}
export function CampaignCard({campaign:c}:{campaign:any}){return <a className="campaign-card" href={'/kampanya/'+c.id}><div className="campaign-visual"><div className="creator-initial">{c.owner_name?.slice(0,1)||'K'}</div><span className="pill">{c.platform}</span></div><div className="campaign-body"><div className="subtle">{c.owner_name} · {c.category}</div><h3>{c.title}</h3><p>{c.description.slice(0,100)}{c.description.length>100?'…':''}</p><div className="stat-row"><div><strong>{money(c.rate)}</strong><small>1.000 uygun görüntülenme</small></div><ArrowUpRight size={19}/></div><hr className="divider"/><div className="stat-row"><small>Klip başına en fazla</small><strong style={{fontSize:14}}>{money(c.cap)}</strong></div><Progress value={Math.min(100,100*(c.used||0)/c.budget)} className="h-1.5 mt-4 mb-3"/><div className="stat-row"><small>Ayrılabilir bütçe</small><span className="money text-sm">{money(Math.max(0,c.budget-(c.used||0)))}</span></div></div></a>}
export function CopyButton({value}:{value:string}){const [copied,setCopied]=useState(false);return <button type="button" className="btn btn-small btn-secondary" onClick={async()=>{try{await navigator.clipboard.writeText(value);setCopied(true);setTimeout(()=>setCopied(false),2000)}catch{setCopied(false)}}}>{copied?<Check size={14}/>:<Copy size={14}/>} {copied?'Kopyalandı':'Kopyala'}</button>}
