import {sqliteTable,text,integer,index,uniqueIndex,check} from 'drizzle-orm/sqlite-core';
import {sql} from 'drizzle-orm';
export const users=sqliteTable('users',{id:text('id').primaryKey(),email:text('email').notNull(),phone:text('phone').notNull().default(''),name:text('name').notNull(),role:text('role').notNull(),status:text('status').notNull().default('active'),iban:text('iban').notNull().default(''),accountName:text('account_name').notNull().default(''),socialUrl:text('social_url').notNull().default(''),verified:integer('verified').notNull().default(0),createdAt:integer('created_at').notNull(),termsVersion:text('terms_version').notNull().default('2026-09-18')},t=>[check('user_role',sql`${t.role} in ('creator','clipper','admin')`)]);
export const owners=sqliteTable('admin_owner',{slot:integer('slot').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),createdAt:integer('created_at').notNull()},t=>[check('single_owner',sql`${t.slot}=1`)]);
export const settings=sqliteTable('settings',{key:text('key').primaryKey(),value:text('value').notNull()});
export const operations=sqliteTable('operations',{id:text('id').primaryKey(),actor:text('actor').notNull(),action:text('action').notNull(),createdAt:integer('created_at').notNull()});
export const deposits=sqliteTable('deposits',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),amount:integer('amount').notNull(),status:text('status').notNull().default('pending'),sender:text('sender').notNull(),transferDate:text('transfer_date').notNull(),reference:text('reference').notNull(),bankSnapshot:text('bank_snapshot').notNull(),proofId:text('proof_id'),bankRef:text('bank_ref'),note:text('note').notNull().default(''),createdAt:integer('created_at').notNull(),reviewedAt:integer('reviewed_at'),reviewedBy:text('reviewed_by')},t=>[index('idx_deposits_user').on(t.userId),uniqueIndex('deposit_bank_ref_unique').on(t.bankRef),check('deposit_amount',sql`${t.amount}>0`)]);
export const campaigns=sqliteTable('campaigns',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull().references(()=>users.id),title:text('title').notNull(),description:text('description').notNull(),rules:text('rules').notNull(),sourceUrl:text('source_url').notNull(),platform:text('platform').notNull(),category:text('category').notNull(),budget:integer('budget').notNull(),cap:integer('cap').notNull(),rate:integer('rate').notNull(),feeBps:integer('fee_bps').notNull(),status:text('status').notNull().default('pending'),createdAt:integer('created_at').notNull(),deadline:integer('deadline').notNull(),note:text('note').notNull().default('')},t=>[index('idx_campaign_owner').on(t.ownerId),index('idx_campaign_status').on(t.status),check('campaign_money',sql`${t.budget}>0 AND ${t.cap}>0 AND ${t.cap}<=${t.budget} AND ${t.rate}>0 AND ${t.feeBps}>=0 AND ${t.feeBps}<=10000`)]);
export const clips=sqliteTable('clips',{id:text('id').primaryKey(),campaignId:text('campaign_id').notNull().references(()=>campaigns.id),userId:text('user_id').notNull().references(()=>users.id),status:text('status').notNull().default('draft'),draftUrl:text('draft_url').notNull().default(''),videoUrl:text('video_url'),videoKey:text('video_key'),cap:integer('cap').notNull(),eligibleViews:integer('eligible_views').notNull().default(0),totalViews:integer('total_views').notNull().default(0),earned:integer('earned').notNull().default(0),createdAt:integer('created_at').notNull(),expiresAt:integer('expires_at').notNull(),publishedAt:integer('published_at'),measurementEnds:integer('measurement_ends'),reviewEnds:integer('review_ends'),lastMeasuredAt:integer('last_measured_at'),note:text('note').notNull().default(''),settledAt:integer('settled_at')},t=>[index('idx_clips_campaign_status').on(t.campaignId,t.status),index('idx_clips_user').on(t.userId),uniqueIndex('clip_user_campaign').on(t.campaignId,t.userId),uniqueIndex('clip_video_unique').on(t.videoKey),check('clip_values',sql`${t.cap}>0 AND ${t.earned}>=0 AND ${t.earned}<=${t.cap} AND ${t.eligibleViews}>=0 AND ${t.totalViews}>=${t.eligibleViews}`)]);
export const measurements=sqliteTable('measurements',{id:text('id').primaryKey(),clipId:text('clip_id').notNull().references(()=>clips.id),totalViews:integer('total_views').notNull(),eligibleViews:integer('eligible_views').notNull(),source:text('source').notNull(),note:text('note').notNull(),observedAt:integer('observed_at').notNull(),createdAt:integer('created_at').notNull(),actor:text('actor').notNull()},t=>[index('idx_measurements_clip').on(t.clipId)]);
export const withdrawals=sqliteTable('withdrawals',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),amount:integer('amount').notNull(),iban:text('iban').notNull(),accountName:text('account_name').notNull(),status:text('status').notNull().default('pending'),bankRef:text('bank_ref'),note:text('note').notNull().default(''),createdAt:integer('created_at').notNull(),reviewedAt:integer('reviewed_at'),reviewedBy:text('reviewed_by')},t=>[index('idx_withdrawals_user').on(t.userId),uniqueIndex('withdrawal_bank_ref_unique').on(t.bankRef),check('withdrawal_amount',sql`${t.amount}>0`)]);
export const ledger=sqliteTable('ledger',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),amount:integer('amount').notNull(),kind:text('kind').notNull(),reference:text('reference').notNull(),createdAt:integer('created_at').notNull()},t=>[index('idx_ledger_user').on(t.userId),uniqueIndex('ledger_event').on(t.kind,t.reference)]);
export const tickets=sqliteTable('tickets',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),subject:text('subject').notNull(),message:text('message').notNull(),reference:text('reference').notNull().default(''),response:text('response').notNull().default(''),status:text('status').notNull().default('open'),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull()},t=>[index('idx_tickets_user').on(t.userId)]);
export const uploads=sqliteTable('uploads',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),key:text('key').notNull(),name:text('name').notNull(),mime:text('mime').notNull(),size:integer('size').notNull(),createdAt:integer('created_at').notNull()});
export const audit=sqliteTable('audit',{id:text('id').primaryKey(),actor:text('actor').notNull(),action:text('action').notNull(),target:text('target').notNull(),details:text('details').notNull(),createdAt:integer('created_at').notNull()},t=>[index('idx_audit_date').on(t.createdAt)]);
export const rateLimits=sqliteTable('rate_limits',{key:text('key').primaryKey(),count:integer('count').notNull(),expires:integer('expires').notNull()});

export const credentials=sqliteTable('credentials',{userId:text('user_id').primaryKey().references(()=>users.id),email:text('email').notNull(),passwordHash:text('password_hash').notNull(),recoveryHash:text('recovery_hash').notNull()},t=>[uniqueIndex('credentials_email').on(t.email)]);
export const sessions=sqliteTable('sessions',{hash:text('hash').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),expiresAt:integer('expires_at').notNull()},t=>[index('sessions_user').on(t.userId),index('sessions_expires').on(t.expiresAt)]);
